/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matrizjc;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Prop extends javax.swing.JInternalFrame {

    /**
     * Creates new form Prop
     */
    DefaultTableModel modeloA=new DefaultTableModel(); 
DefaultTableModel modeloB=new DefaultTableModel();
DefaultTableModel modeloC =new DefaultTableModel();

    public static String filas1="" ;
    public static String columnas1="";
    public static String filas2="" ;
    public static String columnas2="";
    public Prop() {
        initComponents();
        this.setResizable(false);
    }
private void carga(){
    modeloA.setColumnCount(2);
    modeloA.setRowCount(2);
    modeloB.setColumnCount(2);
    modeloB.setRowCount(2);
    jTable1.setModel(modeloA);
    jTable2.setModel(modeloB);
    modeloC.setColumnCount(2);
    modeloC.setRowCount(2);
    jTable3.setModel(modeloC);
}
      private void genA(int fil,int col){
    
    modeloA.setRowCount(fil);
    modeloA.setColumnCount(col);
    jTable1.setModel(modeloA);
}
private void genB(int fil,int col){
    modeloB.setRowCount(fil);
    modeloB.setColumnCount(col);
    jTable2.setModel(modeloB);
}
private void genC(int fil,int col){
    modeloC.setColumnCount(col);
    modeloC.setRowCount(fil);
    jTable3.setModel(modeloC);}
   
      public void mostrarEspiral(int matriz[][] , int f,int c){
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(f);
        model.setColumnCount(c);
        for (int i = 1; i < f+1; i++) {
            for (int j = 1; j < c+1; j++) {
                jTable3.setValueAt(matriz[i][j], i-1, j-1);
            }
        }
    }
  
    private int [][] generarEspiral(int n, int x ){
        int [][] matriz = new int [n+1][n+1];
        
        
            for (int i = 1; i <= n/2; i++) {
                for (int j = i; j <=n-i; j++) {
                    matriz[i][j]=x;
                    x++;
                }
                for (int j = i; j <= n-i; j++) {
                    matriz[i][n-i+1]=x;
                    x++;
                }
                for (int j = n-i+1; j >=i+1; j--) {
                    matriz[n-i+1][j]=x;
                    x++;
                }
                for (int j = n-i+1; j >=i+1; j--) {
                    matriz[j][i]=x;
                    x++;
                }
            }
            if(n%2==1){
            matriz[n/2+1][n/2+1]=x;
            }
        return matriz;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jButtonEspiral = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabelMatriz9 = new javax.swing.JLabel();
        jLabelFilas4 = new javax.swing.JLabel();
        jLabelColumnas4 = new javax.swing.JLabel();
        txtColumna1 = new javax.swing.JTextField();
        txtFila1 = new javax.swing.JTextField();
        jLabelMatriz10 = new javax.swing.JLabel();
        txtFila2 = new javax.swing.JTextField();
        txtColumna2 = new javax.swing.JTextField();
        jButtonGenerar = new javax.swing.JButton();
        jButtonSuma = new javax.swing.JButton();
        jButtonResta = new javax.swing.JButton();
        jButtonMultiplicacion = new javax.swing.JButton();
        jButtonTranspuesta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DarkIcon.png"))); // NOI18N

        jPanel6.setFocusable(false);

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane14.setViewportView(jTable2);

        jLabel14.setText("Primera Matriz");

        jButtonEspiral.setText("Generar Espiral");
        jButtonEspiral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEspiraljButtonEspiralActionPerformed(evt);
            }
        });

        jLabel15.setText("Segunda Matriz");

        jButton9.setText("Habilitar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9jButton1ActionPerformed(evt);
            }
        });

        jButton10.setText("Habilitar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10jButton2ActionPerformed(evt);
            }
        });

        jLabelMatriz9.setText("Primera Matriz");

        jLabelFilas4.setText("Filas");

        jLabelColumnas4.setText("Columnas");

        txtFila1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFila1jTextFieldFilasPMActionPerformed(evt);
            }
        });

        jLabelMatriz10.setText("Segunda Matriz");

        txtColumna2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtColumna2KeyPressed(evt);
            }
        });

        jButtonGenerar.setText("GENERAR MATRIZ");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarjButtonGenerarActionPerformed(evt);
            }
        });

        jButtonSuma.setText("Sumar");
        jButtonSuma.setEnabled(false);
        jButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumajButtonSumaActionPerformed(evt);
            }
        });

        jButtonResta.setText("Restar");
        jButtonResta.setEnabled(false);
        jButtonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestajButtonRestaActionPerformed(evt);
            }
        });

        jButtonMultiplicacion.setText("Mutiplicar");
        jButtonMultiplicacion.setEnabled(false);
        jButtonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacionjButtonMultiplicacionActionPerformed(evt);
            }
        });

        jButtonTranspuesta.setText("Transpuesta");
        jButtonTranspuesta.setEnabled(false);
        jButtonTranspuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTranspuestajButtonTranspuestaActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane13.setViewportView(jTable3);

        jLabel13.setText("Matriz Solicitada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane16.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelFilas4)
                        .addGap(46, 46, 46)
                        .addComponent(jLabelMatriz9)
                        .addGap(54, 54, 54)
                        .addComponent(jLabelMatriz10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabelColumnas4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtFila1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFila2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtColumna1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtColumna2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton10))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9))
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButtonGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(39, 39, 39)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonEspiral, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonMultiplicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonTranspuesta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(63, 63, 63))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMatriz10)
                            .addComponent(jLabelMatriz9))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFila1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFila2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFilas4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtColumna1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColumna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelColumnas4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jButton10))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGenerar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonResta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMultiplicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTranspuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEspiral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEspiraljButtonEspiralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEspiraljButtonEspiralActionPerformed
jTable3.setEnabled(false);
        jTable2.setEnabled(false);
        jTable2.setEnabled(false);
        try{
        int n = Integer.parseInt(txtFila1.getText());
        mostrarEspiral(generarEspiral(n,1),n,n);  
        }catch(java.lang.NullPointerException|java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingrese los datos necesarios \n Se toma el valor de filas de Primera Matriz\nERROR: "+e,("PHENOM SOFT"),2);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEspiraljButtonEspiralActionPerformed

    private void jButton9jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9jButton1ActionPerformed
        jTable2.setEnabled(true);
    }//GEN-LAST:event_jButton9jButton1ActionPerformed

    private void jButton10jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10jButton2ActionPerformed
jTable2.setEnabled(true);        
    }//GEN-LAST:event_jButton10jButton2ActionPerformed

    private void txtFila1jTextFieldFilasPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFila1jTextFieldFilasPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFila1jTextFieldFilasPMActionPerformed

    private void jButtonGenerarjButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarjButtonGenerarActionPerformed
 try{
         
            
        int Afila=Integer.parseInt(txtFila1.getText());
        int Acol=Integer.parseInt(txtColumna1.getText());
        int Bfila=Integer.parseInt(txtFila2.getText());
        int Bcol=Integer.parseInt(txtColumna2.getText());
        
        genA(0,0);
            genB(0,0);
            genC(0,0);
            jButtonMultiplicacion.setEnabled(false);
            jButtonSuma.setEnabled(false);
            jButtonResta.setEnabled(false);
            jButtonTranspuesta.setEnabled(false);
        
        if(Acol==Bfila){
            genA(Afila,Acol);
            genB(Bfila,Bcol);
            jButtonMultiplicacion.setEnabled(true);
            jButtonSuma.setEnabled(false);
            jButtonResta.setEnabled(false);
        }
         if(Acol==Bcol&Afila==Bfila){
            genA(Afila,Acol);
            genB(Bfila,Bcol);
            jButtonMultiplicacion.setEnabled(false);
           jButtonSuma.setEnabled(true);
            jButtonResta.setEnabled(true); 
            if(Acol==Bfila){jButtonMultiplicacion.setEnabled(true);}
        }
        if(Afila>1&Acol>1){
            genA(Afila,Acol);
            jButtonTranspuesta.setEnabled(true);}else{jButtonTranspuesta.setEnabled(false);
        }
        }catch(java.lang.RuntimeException e){
            JOptionPane.showMessageDialog(this, "No se acepta letras  o\nespacios en blanco\nERROR: "+e,("PHENOM SOFT"),2);
            
        }        
    }//GEN-LAST:event_jButtonGenerarjButtonGenerarActionPerformed

    private void jButtonSumajButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumajButtonSumaActionPerformed
 try{
     
        jTable2.setEnabled(true);
        jTable2.setEnabled(true);
        int r,i,j,S=0;
        int Afila=Integer.parseInt(txtFila1.getText());
        int Bcol=Integer.parseInt(txtColumna2.getText());
        genC(Afila,Bcol);
        for(i=0;i<Afila;i++){
        for(j=0;j<Bcol;j++){
            r=Integer.parseInt(modeloA.getValueAt(i, j).toString())+Integer.parseInt(modeloB.getValueAt(i, j).toString());
        
        modeloC.setValueAt(r+"", i, j);
        r=0;
        }
        }}catch(java.lang.RuntimeException e){
            JOptionPane.showMessageDialog(null, "No se permiten letras o casilleros en blanco\nERROR: "+e,("PHENOM SOFT"),2);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error inesperado\nERROR: "+e,("PHENOM SOFT"),2);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSumajButtonSumaActionPerformed

    private void jButtonRestajButtonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestajButtonRestaActionPerformed
jTable2.setEnabled(true);
        jTable2.setEnabled(true);
        try{
        int r,i,j,S=0;
        int Afila=Integer.parseInt(txtFila1.getText());
        int Bcol=Integer.parseInt(txtColumna2.getText());
        genC(Afila,Bcol);
        for(i=0;i<Afila;i++){
        for(j=0;j<Bcol;j++){
            r=Integer.parseInt(modeloA.getValueAt(i, j).toString())-Integer.parseInt(modeloB.getValueAt(i, j).toString());
        
        modeloC.setValueAt(r+"", i, j);
        r=0;
        }}}catch(java.lang.NumberFormatException|java.lang.NullPointerException e){
            JOptionPane.showMessageDialog(null, "No se permiten letras o casilleros en blanco\nERROR: "+e,("PHENOM SOFT"),2);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRestajButtonRestaActionPerformed

    private void jButtonMultiplicacionjButtonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacionjButtonMultiplicacionActionPerformed
jTable2.setEnabled(true);
        jTable2.setEnabled(true);
        try{        
            int r,i,j,S=0;
            int Afila=Integer.parseInt(txtFila1.getText());
            int Acol=Integer.parseInt(txtColumna1.getText());
            int Bfila=Integer.parseInt(txtFila2.getText());
            int Bcol=Integer.parseInt(txtColumna2.getText());
            genC(Afila,Bcol);
            for(i=0;i<Afila;i++){
                for(j=0;j<Bcol;j++){
                    for(r=0;r<Acol;r++){
                        S=S+Integer.parseInt(modeloA.getValueAt(i, r).toString())*Integer.parseInt(modeloB.getValueAt(r, j).toString());
                    }
                    modeloC.setValueAt(S+"", i, j);
                    S=0;
                }
            }
        }catch(java.lang.NullPointerException |java.lang.NumberFormatException e){    
            JOptionPane.showMessageDialog(null, "No se permiten letras o casilleros en blanco\nERROR: "+e,("PHENOM SOFT"),2);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMultiplicacionjButtonMultiplicacionActionPerformed

    private void jButtonTranspuestajButtonTranspuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTranspuestajButtonTranspuestaActionPerformed
        int Af=Integer.parseInt(txtFila1.getText());
        int Ac=Integer.parseInt(txtColumna1.getText());
        genC(Ac,Af);
        jTable2.setEnabled(true);
        jTable3.setEnabled(false);
        jTable2.setEnabled(false);
        int r = 0;
        int Afila=0;
        int Bfil=0;
        try{
            String Afilas="",Bfilas="";
            Afilas=txtFila1.getText();
            Bfilas = txtColumna1.getText();
        
        Afila = Integer.parseInt(Afilas);
        Bfil = Integer.parseInt(Bfilas);
        
        int mat[][] = new int [Afila][Bfil];
        for (int i = 0; i < Afila; i++) {
            for (int j = 0; j < Bfil; j++) {
                r=Integer.parseInt(modeloA.getValueAt(i, j).toString());
                jTable3.setValueAt(r+"", j, i);
                r=0;
            }
            
        }
        
        }catch(java.lang.NullPointerException | java.lang.NumberFormatException e){//hay espacios en blanco --- no se relleno datos
            JOptionPane.showMessageDialog(null, "No se permite letras o casilleros en blanco\nERROR: "+e,("PHENOM SOFT"),2);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTranspuestajButtonTranspuestaActionPerformed

    private void txtColumna2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColumna2KeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){ 
            jButtonGenerar.doClick();
            jButtonGenerar.requestFocus();
        }     
        
    }//GEN-LAST:event_txtColumna2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonEspiral;
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JButton jButtonMultiplicacion;
    private javax.swing.JButton jButtonResta;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JButton jButtonTranspuesta;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabelColumnas4;
    private javax.swing.JLabel jLabelFilas4;
    private javax.swing.JLabel jLabelMatriz10;
    private javax.swing.JLabel jLabelMatriz9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtColumna1;
    private javax.swing.JTextField txtColumna2;
    private javax.swing.JTextField txtFila1;
    private javax.swing.JTextField txtFila2;
    // End of variables declaration//GEN-END:variables
}
